version: 0.2

phases:
  install:
    commands:
      - pip install yamllint
      - pip install awscli
      - pip install taskcat
      - apt update
      - apt install git -y
  build:
    commands:
      - ls
      - /usr/local/bin/yamllint *.yml
