version: 0.2

phases:
  install:
    commands:
      - pip install yamllint
      - pip install awscli
      - pip install taskcat
      - apt update
      - apt install git -y
  build:
    commands:
      - git clone https://github.com/lcc2207/cbcloudformation.git
      - /usr/local/bin/yamllint *.yml
      - ls -l
